name: kubelogin # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: kubelogin
summary: Azure kubelogin # 79 char long summary
description: |
  A Kubernetes credential (exec) plugin implementing azure authentication.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

plugs:
  dot-kubeconfig-access:
    interface: personal-files
    read:
    - $HOME/.kube/config
    write:
    - $HOME/.kube/cache/kubelogin

apps:
  kubelogin:
    command: kubelogin
    plugs:
    - home
    - network
    - dot-kubeconfig-access

parts:
  kubelogin:
    # See 'snapcraft plugins'
    build-snaps:
      - go
    plugin: make
    override-build: |
      make
      snapcraftctl set-version $(git describe --tags)
      find . -iname 'kubelogin' -exec cp -r {} $SNAPCRAFT_PART_INSTALL/ \;

    source-type: git
    source: https://github.com/Azure/kubelogin
